# Phase 8 staging environment overrides (docker-compose.staging.yml)
$env:DB_CONNECTION = 'mysql'
$env:DB_HOST = '127.0.0.1'
$env:DB_PORT = '3307'
$env:DB_DATABASE = 'diyar_staging'
$env:DB_USERNAME = 'diyar_staging'
$env:DB_PASSWORD = 'staging_secret'
$env:CACHE_STORE = 'redis'
$env:REDIS_HOST = '127.0.0.1'
$env:REDIS_PORT = '6380'
$env:REDIS_PASSWORD = ''
$env:REDIS_PREFIX = 'diyar-phase8-'
$env:QUEUE_CONNECTION = 'sync'
$env:SESSION_DRIVER = 'array'
