[program:diyar-queue-critical]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/diyar/backend/artisan queue:work redis --queue=critical --sleep=1 --tries=5 --timeout=120 --max-jobs=1000 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-queue-critical.log
stopwaitsecs=3600

[program:diyar-queue-high]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/diyar/backend/artisan queue:work redis --queue=notifications-high,notifications --sleep=2 --tries=5 --timeout=120 --max-jobs=1000 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-queue.log
stopwaitsecs=3600

[program:diyar-queue-broadcast]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/diyar/backend/artisan queue:work redis --queue=notifications-low,broadcast --sleep=3 --tries=5 --timeout=180 --max-jobs=500 --max-time=3600 --memory=192
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-queue-broadcast.log
stopwaitsecs=3600

[program:diyar-queue-chat]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/diyar/backend/artisan queue:work redis --queue=chat,chat-low,default --sleep=2 --tries=5 --timeout=120 --max-jobs=1000 --max-time=3600 --memory=128
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-queue-chat.log
stopwaitsecs=3600

[program:diyar-reverb]
process_name=%(program_name)s
command=php /var/www/diyar/backend/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-reverb.log

[program:diyar-scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while true; do php /var/www/diyar/backend/artisan schedule:run --verbose --no-interaction; sleep 60; done"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/diyar-scheduler.log
