#Requires -Version 5.1
<#
.SYNOPSIS
  Start full local dev stack in one command (Docker API + Vite + nginx gateway).

.DESCRIPTION
  Opens http://diyar.local:8080 for the React storefront.
  Docker alone (:8093) is API-only — the frontend is always Vite in local dev.

  Equivalent to running the three scripts manually, but in one step.
#>

param(
    [switch]$SkipDockerBuild,
    [switch]$NoBrowser
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
Set-Location $Root

. (Join-Path $PSScriptRoot 'Sync-ProductionEnv.ps1')
. (Join-Path $PSScriptRoot 'Ensure-DiyarHostsEntry.ps1')

$EnvFile = Join-Path $Root 'deploy/docker/production.env'
$Example = Join-Path $Root 'deploy/docker/production.env.local.example'
if (-not (Test-Path $EnvFile)) {
    Copy-Item $Example $EnvFile
    Write-Host "Created $EnvFile from local example."
}

$backend = Join-Path $Root 'backend'
Push-Location $backend
$appKey = (php artisan key:generate --show 2>$null | Select-Object -Last 1).Trim()
Pop-Location
if ($appKey) {
    (Get-Content $EnvFile -Raw) -replace 'APP_KEY=.*', "APP_KEY=$appKey" | Set-Content $EnvFile -NoNewline
}

$network = Sync-ProductionEnv -Root $Root
$gatewayUrl = $network.GatewayUrl
$httpPort = $network.HttpPort
$frontendRoot = Join-Path $Root 'frontend'

Ensure-DiyarHostsEntry -Hostname $network.GatewayHost

Write-Host '=== DIYAR local dev (one command) ===' -ForegroundColor Cyan
Write-Host ''

# 1) Docker API stack
Write-Host '[1/3] Docker API (internal :8093)...' -ForegroundColor Yellow
$composeArgs = @(
    'compose', '-f', 'docker-compose.production.yml',
    '--env-file', 'deploy/docker/production.env',
    'up', '-d'
)
if (-not $SkipDockerBuild) {
    $composeArgs += '--build'
}
& docker @composeArgs
if ($LASTEXITCODE -ne 0) {
    throw 'Docker stack failed to start.'
}

Write-Host '      Waiting for API health...'
Start-Sleep -Seconds 12
try {
    Invoke-WebRequest -Uri "http://127.0.0.1:${httpPort}/api/v1/health/live" -UseBasicParsing | Out-Null
    Write-Host '      API OK' -ForegroundColor Green
} catch {
    Write-Warning '      API not ready yet — check: docker compose -f docker-compose.production.yml logs nginx app'
}

# 2) Vite frontend (new window — must stay running)
Write-Host '[2/3] Vite frontend (new window, :3000)...' -ForegroundColor Yellow

$envFile = Join-Path $frontendRoot '.env.prod-api.local'
@(
    "# Auto-generated by scripts/local/start-local-dev.ps1"
    "# Browser URL: $gatewayUrl"
    "VITE_API_URL=/api/v1"
    "VITE_BACKEND_URL="
    "VITE_APP_NAME=DIYAR"
    "VITE_REVERB_APP_KEY=diyar_local_reverb_key"
    "VITE_REVERB_HOST="
    "VITE_REVERB_PORT="
    "VITE_REVERB_SCHEME=http"
    "VITE_PLATFORM_SUPPORT_PHONE=+966500000000"
    "VITE_PLATFORM_SUPPORT_EMAIL=support@diyar.com"
    "VITE_PLATFORM_SUPPORT_HOURS=9:00 - 18:00"
) | Set-Content -Path $envFile -Encoding utf8

$viteCmd = @"
Set-Location '$frontendRoot'
`$env:DIYAR_API_PROXY_TARGET = 'http://127.0.0.1:${httpPort}'
`$env:DIYAR_REVERB_PROXY_TARGET = 'http://127.0.0.1:${httpPort}'
npm run dev:prod-api
"@
Start-Process powershell -ArgumentList @('-NoExit', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', $viteCmd)
Write-Host '      Vite starting in new PowerShell window' -ForegroundColor Green

Write-Host '      Waiting for Vite...'
$viteReady = $false
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 2
    try {
        Invoke-WebRequest -Uri 'http://127.0.0.1:3000' -UseBasicParsing -TimeoutSec 3 | Out-Null
        $viteReady = $true
        break
    } catch {
        # keep waiting
    }
}
if ($viteReady) {
    Write-Host '      Vite OK' -ForegroundColor Green
} else {
    Write-Warning '      Vite still starting — wait for the new window, then refresh the browser.'
}

# 3) Nginx gateway
Write-Host '[3/3] Nginx gateway (:8080)...' -ForegroundColor Yellow
docker compose -f docker-compose.local-gateway.yml up -d
if ($LASTEXITCODE -ne 0) {
    throw 'Local gateway failed to start.'
}
Write-Host '      Gateway OK' -ForegroundColor Green

Write-Host ''
Write-Host '=== Ready ===' -ForegroundColor Cyan
Write-Host "  Storefront (React):  $gatewayUrl"
Write-Host "  API only (no UI):    http://127.0.0.1:${httpPort}/api/v1/health"
Write-Host ''
Write-Host 'Keep the Vite PowerShell window open while you develop.'
Write-Host 'Stop everything: docker compose -f docker-compose.production.yml down; docker compose -f docker-compose.local-gateway.yml down'
Write-Host ''

if (-not $NoBrowser) {
    Start-Process $gatewayUrl
}
