#Requires -Version 5.1
$ErrorActionPreference = 'Stop'

$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$Frontend = Join-Path $Root 'frontend'
Set-Location $Frontend

. (Join-Path $PSScriptRoot 'Sync-ProductionEnv.ps1')
$network = Sync-ProductionEnv -Root $Root
$httpPort = $network.HttpPort

function Stop-PortListener([int]$Port) {
    $connections = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    foreach ($connection in $connections) {
        $processId = $connection.OwningProcess
        if ($processId -and $processId -ne 0) {
            Write-Host "Stopping process $processId listening on port $Port..."
            Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue
        }
    }
}

Stop-PortListener -Port 3000
Stop-PortListener -Port 3001

$proxyTarget = "http://127.0.0.1:${httpPort}"
$envFile = Join-Path $Frontend '.env.prod-api.local'
@(
    "# Auto-generated by scripts/local/start-frontend-prod-api.ps1"
    "# Browser URL: $($network.GatewayUrl) (via start-dev-gateway.ps1)"
    "VITE_API_URL=/api/v1"
    "VITE_BACKEND_URL="
    "VITE_APP_NAME=DIYAR"
    "VITE_REVERB_APP_KEY=diyar_local_reverb_key"
    "VITE_REVERB_HOST="
    "VITE_REVERB_PORT="
    "VITE_REVERB_SCHEME=http"
    "VITE_PLATFORM_SUPPORT_PHONE=+966500000000"
    "VITE_PLATFORM_SUPPORT_EMAIL=support@diyar.com"
    "VITE_PLATFORM_SUPPORT_HOURS=9:00 - 18:00"
) | Set-Content -Path $envFile -Encoding utf8

$env:DIYAR_API_PROXY_TARGET = $proxyTarget
$env:DIYAR_REVERB_PROXY_TARGET = $proxyTarget

Write-Host "Wrote $envFile"
Write-Host "Starting frontend (prod-api mode)..."
Write-Host "  Internal proxy: $proxyTarget"
Write-Host "  Stable URL:     $($network.GatewayUrl)"
Write-Host "  Next step:      ..\scripts\local\start-dev-gateway.ps1"

npm run dev:prod-api
